# Generated by Django 5.1.3 on 2025-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
